services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=_user
      - MONGO_INITDB_ROOT_PASSWORD=_pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: -express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=_pass
      - ME_CONFIG_MONGODB_URL=mongodb://_user:_pass@mongodb:27017/
      - ME_CONFIG_BASICAUTH="false"
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

volumes:
  mongo_data:
